version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testms
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: userpassword
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      UPLOAD_LIMIT: 50M
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db

volumes:
  mysql_data:

networks:
  default:
    driver: bridge
